# Generated by Django 4.2 on 2023-07-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddingapp', '0002_gongmo_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jickgoonjoin',
            name='group',
        ),
        migrations.RemoveField(
            model_name='jickgoonjoin',
            name='member',
        ),
        migrations.RemoveField(
            model_name='team',
            name='gongmo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='gongmo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='gongmo',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='gongmo',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='gongmo',
            name='edit_time',
        ),
        migrations.RemoveField(
            model_name='gongmo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gongmo',
            name='registration_time',
        ),
        migrations.DeleteModel(
            name='Jickgoon',
        ),
        migrations.DeleteModel(
            name='Jickgoonjoin',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
