# Generated by Django 4.2 on 2023-07-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddingapp', '0004_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
    ]
