# Generated by Django 4.2 on 2023-07-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddingapp', '0006_team_jickgoon1_team_jickgoon2_team_jickgoon3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='jickgoon1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='jickgoon2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='jickgoon3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
    ]
