# Generated by Django 4.2 on 2023-07-13 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddingapp', '0007_remove_team_jickgoon1_remove_team_jickgoon2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jickgoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jickgoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddingapp.jickgoon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddingapp.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='jickgoons',
            field=models.ManyToManyField(through='ddingapp.Member', to='ddingapp.jickgoon'),
        ),
    ]
