# Generated by Django 4.2 on 2023-07-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddingapp', '0012_remove_notification_message_notification_jickgoon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
