# Generated by Django 4.2 on 2023-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddingapp', '0015_member_num_of_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='design_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='dev_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='plan_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
