# Generated by Django 4.2 on 2023-07-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddingapp', '0017_remove_member_num_of_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='call',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='teamname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
